name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Check for requirements.txt
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found"
          exit 1
        fi

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Make scripts executable
      run: chmod +x pipeline.sh tests.sh

    - name: Run pipeline
      run: bash pipeline.sh

    - name: Run tests
      run: bash tests.sh
